---
title: "CorrigeDataCamp"
author: "Aleix Cebrián Valero"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
library(stringi)
lista_carpetas_alumnos <- list.files(path = "data/EntregaAlumnos")

lista_carpetas_alumnos[1]

#nombre_completo <- strsplit(split = "_", x = lista_carpetas_alumnos, fixed = T)
apellidos <- str_split_i(lista_carpetas_alumnos, ", ", 1)
nombres <- str_split_i(str_split_i(lista_carpetas_alumnos, ", ", 2), "_", 1)

readLines("data/EntregaAlumnos/Adán Alegre, Alejandro_11814290_assignsubmission_file/puntos.txt")

archivo <- file(paste0("data/EntregaAlumnos/",lista_carpetas_alumnos[10],"/puntos.txt"))

linea <- readLines(archivo)
close(archivo)


leer_txt <- function(lista_carpetas_alumnos) {
  lista_resultados <- list(length = length(lista_carpetas_alumnos))
  for (i in 1:length(lista_carpetas_alumnos)) {
      if (file.exists(paste0("data/EntregaAlumnos/",lista_carpetas_alumnos[i],"/",lista_nombres_ficheros_txt[i]))) {
        archivo <- file(paste0("data/EntregaAlumnos/",lista_carpetas_alumnos[i],"/",lista_nombres_ficheros_txt[i]))
        linea <- readLines(archivo, warn = F)
        close(archivo)
        lista_resultados[i] = suppressWarnings(as.integer(linea))
      } else {
        lista_resultados[i] = NA
      }
    }
  return(lista_resultados)
}

lista_resultados <- leer_txt(lista_carpetas_alumnos)
```

```{r}
nombres_ficheros <- list.files(paste0("data/EntregaAlumnos/", lista_carpetas_alumnos,"/"))

stri_detect_regex(nombres_ficheros,".txt")

hallar_nombres <- function(lista_carpetas_alumnos) {
  # 1. Inicializamos la lista correctamente (como vimos antes)
  lista_nom_fichero <- vector("list", length(lista_carpetas_alumnos))
  
  # 2. Bucle corregido con 1:length()
  for (i in 1:length(lista_carpetas_alumnos)) {
    
    # Construimos la ruta de la carpeta
    ruta_carpeta <- paste0("data/EntregaAlumnos/", lista_carpetas_alumnos[i], "/")
    
    # 3. La magia de R: list.files busca SOLO los .txt automáticamente
    # El patrón "\\.txt$" significa "que termine exactamente en .txt"
    archivos_txt <- list.files(path = ruta_carpeta, pattern = "\\.txt$")
    
    # 4. Comprobamos si encontró algo
    if (length(archivos_txt) > 0) {
      # Guardamos el primer .txt que encuentre (o todos, si lo prefieres)
      lista_nom_fichero[[i]] <- archivos_txt[1]
    } else {
      # Si no hay ningún .txt, guardamos NA para no romper el orden
      lista_nom_fichero[[i]] <- NA
    }
  }
  
  # 5. El return va FUERA del bucle, al final de la función
  return(lista_nom_fichero)
}

lista_nombres_ficheros_txt <- hallar_nombres(lista_carpetas_alumnos)
```

```{r}
library(tibble)

evalua_df <- tibble(apellidos = apellidos, puntos = as.numeric(lista_resultados), NomFile = as.character(lista_nombres_ficheros_txt), Puntos = as.character(lista_contenido))

```

```{r}
library(writexl)
lista_contenido = list(length = length(lista_carpetas_alumnos))
for (i in 1:length(lista_carpetas_alumnos)) {
    if (file.exists(paste0("data/EntregaAlumnos/",lista_carpetas_alumnos[i],"/",lista_nombres_ficheros_txt[i]))) {
      archivo <- file(paste0("data/EntregaAlumnos/",lista_carpetas_alumnos[i],"/",lista_nombres_ficheros_txt[i]))
      linea <- readLines(archivo, warn = F)
      close(archivo)
      lista_contenido[i] = suppressWarnings(as.character(linea))
    } else {
      lista_resultados[i] = NA
    }
}

write_xlsx(evalua_df, "NotasRIntermedio.xlsx")

```

```{r}
library(dplyr)
library(readxl)
df_alumnos <- read_excel("AlumnosTD25_26.xlsx")
names(df_alumnos) <- c("nombres", "apellidos", "nom_usuario", "id", "correo")
df_total <- df_alumnos %>% inner_join(evalua_df, by = "apellidos")
write.xlsx(df_total,"AlumnosNotas.xlsx")
```





